# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/"
    insecure-external-code-execution: "allow"
    registries: "*"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
